microsoft/DirectXMesh

DirectXMesh/DirectXMeshAdjacency.cpp
DirectXMesh/DirectXMeshNormals.cpp
DirectXMesh/DirectXMeshTangentFrame.cpp

The latest DirectXMath use a new ``_XM_NO_XMVECTOR_OVERLOADS_`` option in order to support building with clang--for details see [this blog post](https://blogs.msdn.microsoft.com/chuckw/2017/06/28/directxmath-3-11/). This means all client code that wants to build with clang also needs to avoid using DirectXMath XMVECTOR overloads.
This updates DirectXMesh's use of DirectXMath to build without the overloads.

Fix compiler errors (clang)

---

DirectXMesh/DirectXMeshRemap.cpp

``OptimizeVertices`` returns a vertexRemap array that matches the D3DX public API, namely: ``oldLoc = vertexRemap[newLoc]``. This is consistent with OptimizeFaces faceRemap.
Unfortunately, the remap functions interpreted the vertexRemap incorrectly as: ``newLoc = vertexRemap[oldLoc]``.
This error became obvious when doing better vertex texture fetch analysis and the ``WeldVertices`` operation.
This change fixes the remap functions.

Remap functions had vertexMaps backwards

---

Meshconvert/Mesh.cpp
Meshconvert/Mesh.h
Meshconvert/MeshOBJ.cpp
Utilities/WaveFrontReader.h

This adds the ability to define an RMA material within the OBJ's MTL via the command `map_RMA` or `map_occlusionRoughnessMetallic`.
This replaces the current implementation of using a presumed filename from the albeto name, often causing errors when using the PBREffectFactory.

Ability to define RMA texture in OBJ's MTL.

---

.gitignore
DirectXMesh/CMakeLists.txt
DirectXMesh/CMakeSettings.json
DirectXMesh/DirectXMesh.h
DirectXMesh/DirectXMeshAdjacency.cpp
DirectXMesh/DirectXMeshOptimizeLRU.cpp
DirectXMesh/DirectXMeshP.h
DirectXMesh/DirectXMeshUtil.cpp
DirectXMesh/DirectXMeshVBWriter.cpp

With VS 2019 Update 1 supporting the clang/LLVM toolset, I've formally added CMake files as well as addressed a number of clang warnings.

Add CMake project and fix clang warnings

---

Meshconvert/Mesh.cpp
Meshconvert/Mesh.h
Meshconvert/Meshconvert.cpp

For ``VBO`` and ``CMO``, the vertex formats are fixed. For ``SDKMESH`` they are variable.
This PR adds switches to let you set alternative formats for vertex normals/tangents/bi-tangents, vertex colors, and vertex texture coordinates. These options let you customize the vertex format and therefore overall size.

Meshconvert: updated with -fn, -fuv, and -fc switches

---

.nuget/directxmesh-config.cmake.in
CMakeLists.txt

This PR updates the CMake support in DirectXMesh to support ``find_package(directxmesh CONFIG)``:
```
find_package(directxmesh CONFIG REQUIRED)
target_link_libraries(foo Microsoft::DirectXMesh)
```
The package supports two components. By default, you get the DirectXMesh.lib component which is "library":
```
find_package(directxmesh CONFIG REQUIRED COMPONENTS library)
```
You can opt-in to getting the ``WaveFrontReader.h`` as a component named "utils".
```
find_package(directxmesh CONFIG REQUIRED COMPONENTS library utils)
target_link_libraries(foo Microsoft::DirectXMesh Microsoft::DirectXMesh::Utilities)
```

CMake package support

---

CMakeLists.txt
DirectXMesh/DirectXMesh.h
DirectXMesh/DirectXMeshP.h
Meshconvert/Mesh.cpp
Meshconvert/Mesh.h
Meshconvert/Meshconvert.cpp

Reviewed all the C++ standard library header usage and normalized usage for improved conformance.
* ``size_t`` requires ``cstddef``
* ``memcpy``, ``memcpy_s`` is officially in ``cstring``
* Use ``cassert`` instead of ``assert.h``
* ``std::move`` is in ``utility``
> The non-standard malloc.h is still being included for ``_aligned_malloc`` / ``_aligned_free``. To be conformant, I should update it to use ``aligned_alloc`` and ``free`` when building for C++17 which is in ``cstdlib``.
Also trimmed trailing whitespace in these files.

Code review for standard library header usage

---

DirectXMesh/DirectXMesh.h
DirectXMesh/DirectXMeshConcat.cpp
DirectXMesh/DirectXMesh_Desktop_2017.vcxproj
DirectXMesh/DirectXMesh_Desktop_2017.vcxproj.filters
DirectXMesh/DirectXMesh_Desktop_2017_Win10.vcxproj
DirectXMesh/DirectXMesh_Desktop_2017_Win10.vcxproj.filters
DirectXMesh/DirectXMesh_Desktop_2019.vcxproj
DirectXMesh/DirectXMesh_Desktop_2019.vcxproj.filters
DirectXMesh/DirectXMesh_Desktop_2019_Win10.vcxproj
DirectXMesh/DirectXMesh_Desktop_2019_Win10.vcxproj.filters
DirectXMesh/DirectXMesh_GDK_2017.vcxproj
DirectXMesh/DirectXMesh_GDK_2017.vcxproj.filters
DirectXMesh/DirectXMesh_GDK_2019.vcxproj
DirectXMesh/DirectXMesh_GDK_2019.vcxproj.filters
DirectXMesh/DirectXMesh_Windows10_2017.vcxproj
DirectXMesh/DirectXMesh_Windows10_2017.vcxproj.filters
DirectXMesh/DirectXMesh_Windows10_2019.vcxproj
DirectXMesh/DirectXMesh_Windows10_2019.vcxproj.filters
DirectXMesh/DirectXMesh_XboxOneXDK_2017.vcxproj
DirectXMesh/DirectXMesh_XboxOneXDK_2017.vcxproj.filters

Helper for generating mappings when merging meshes.
> Note that these remaps are the *inverse* of the other library remaps. These are ``newLoc = map[oldLoc]`` which is much easier to use when constructing merged meshes. The 'normal' style of maps would require a pair to indicate mesh and oldLoc.

ConcatenateMesh function

---

.nuget/directxmesh_desktop_2017.nuspec
.nuget/directxmesh_desktop_win10.nuspec
.nuget/directxmesh_uwp.nuspec
CMakeLists.txt
Utilities/FlexibleVertexFormat.h

This PR adds a new utility header to the DirectXMesh repo. This contains helper functions for working with Direct3D 9 legacy [FVF codes](https://docs.microsoft.com/en-us/windows/win32/direct3d9/fixed-function-fvf-codes) and Direct3D 9 decls. This is useful for tools parsing through older resources, Xfiles, etc. Also added secure versions of two functions that really need bounds to be SAL annotatable.
> This header does not require any legacy DirectX SDK headers, but will only build for the "Win32 Desktop" partition because it uses ``d3d9.h`` (i.e. it's not usable in UWP apps. If that's an issue, please note that in this review).

FlexibleVertexFormat.h header added to Utilities

---

DirectXMesh/DirectXMeshletGenerator.cpp

If triangle, that have 2 identical indices is ever passed to meshlet generation, it may result in generation of meshlet with vertex count higher than allowed (maxVerts parameter).
If such triangle is added, UniqueVertexIndices will have 2 identical indices.
It's a problem for code calculating whether triangle fit into meshlet.
newCount may be decremented twice for each vertex instead of once,
resulting in lower newCount than it will actually be added later.
So I propose to just cull degenerate triangles.
That will both fix the issue and result in better generated meshlets in cases input geometry have degenerate triangles.

Fixed meshlet verticies overflow in case degenerate triangle is passed

---

DirectXMesh/DirectXMesh.inl

According to the standard, constexpr functions are also inline.

Remove inline specifier from constexpr function

---

.nuget/directxmesh_desktop_2019.nuspec
.nuget/directxmesh_desktop_2019.targets
.nuget/directxmesh_desktop_win10.nuspec
.nuget/directxmesh_desktop_win10.targets
DirectXMesh/DirectXMesh_Desktop_2019.vcxproj
DirectXMesh/DirectXMesh_Desktop_2019_Win10.vcxproj
DirectXMesh/DirectXMesh_Desktop_2022.vcxproj
DirectXMesh/DirectXMesh_Desktop_2022_Win10.vcxproj

Customers using the BinSkim Microsoft security tool will get flagged when using static C++ libraries not built using ``/Qspectre``. This adds the alternative flavor of the libraries to the **directxmesh_desktop_2019** and **directxmesh_desktop_win10** versions of the NuGet package. The targets automatically selects the Spectre version when building with SpectreMitigations enabled.
> This will double the package size from 9 MB to ~18MB which is reasonable.

Add Spectre-mitigated libraries to the NuGet

---

CMakeLists.txt
build/DirectXMesh-GitHub-WSL-11.yml
build/DirectXMesh-GitHub-WSL.yml

Update the WSL build pipelines to validate both Debug and Release configurations.
In addition, this PR introduces a new CMake build option ``DISABLE_MSVC_ITERATOR_DEBUGGING`` to allow clients to disable MSVC's iterator debugging in Debug configuration since this is now the 'default' for clang/LLVM for Windows builds even when not using the ``clang-cl`` driver.

Test Debug and Release for WSL YAML

---

Meshconvert/Meshconvert.cpp
Meshconvert/Meshconvert_Desktop_2019.vcxproj
Meshconvert/Meshconvert_Desktop_2022.vcxproj

The **meshconvert** tool is a Windows command-line tool, and so doesn't follow POSIX utility conventions. This PR, however, adds support for a few specific behaviors:
```
meshconvert --version
```
```
meshconvert --help
```
All paths read from the command-line or from *-flist* files are normalized to the Windows path separator, so the tool now accepts UNIX-style paths or Windows-style paths. In order to allow the input filenames to start with a `/`, you can use `--` as an escape to indicate the 'end of options' which will allow input filenames to start with either `-` or `/`.
```
meshconvert [options] -- /folder/path/to/name/fname.obj
```
> This PR also makes the command-line tool build using C++17 mode.

meshconvert tool updates for some POSIX like support

---

.nuget/directxmesh_desktop_2019.nuspec
.nuget/directxmesh_desktop_win10.nuspec
.nuget/directxmesh_uwp.nuspec
HISTORY.md
README.md

* CMake project updates
* Minor code review
* Retired VS 2017 legacy Xbox One XDK projects
* meshconvert: Updated to support Windows or UNIX-style path separators

March 30, 2023

---

DirectXMesh_Desktop_2019_Win10.sln
DirectXMesh_Desktop_2022_Win10.sln
Meshconvert/Meshconvert_Desktop_2019.vcxproj
Meshconvert/Meshconvert_Desktop_2019_Win10.vcxproj
Meshconvert/Meshconvert_Desktop_2019_Win10.vcxproj.filters
Meshconvert/Meshconvert_Desktop_2022_Win10.vcxproj
Meshconvert/Meshconvert_Desktop_2022_Win10.vcxproj.filters

Adds **meshconvert** to the `_Win10` solutions so it builds with `_WIN32_WINNT=0x0A00` and adds an ARM64 configuration.

ARM64 version of meshconvert tool

---

CMakeLists.txt
README.md

The XBOX_CONSOLE_TARGET variable can be set to ``scarlett`` or ``xboxone`` if built in the appropriate Developer Command Prompt. We don't support ``durango`` for this library anymore.
Also added some warning suppressions for the clang v16 toolset.

CMake minor cleanup

---

CMakeLists.txt
Meshconvert/Meshconvert.cpp
Meshconvert/Meshconvert_Desktop_2019.vcxproj
Meshconvert/Meshconvert_Desktop_2019.vcxproj.filters
Meshconvert/Meshconvert_Desktop_2019_Win10.vcxproj
Meshconvert/Meshconvert_Desktop_2019_Win10.vcxproj.filters
Meshconvert/Meshconvert_Desktop_2022.vcxproj
Meshconvert/Meshconvert_Desktop_2022.vcxproj.filters
Meshconvert/Meshconvert_Desktop_2022_Win10.vcxproj
Meshconvert/Meshconvert_Desktop_2022_Win10.vcxproj.filters
Meshconvert/settings.manifest

Updates **meshconvert** to support very long file names with Windows 10 (Version 1607) or later.
> Note that the tool does not support UNC style ``\\?\`` long paths as those are not supported by ``std::filesystem``.

meshconvert updated to support long path names with Windows 10

---

.nuget/directxmesh_desktop_2019.nuspec
.nuget/directxmesh_desktop_win10.nuspec
.nuget/directxmesh_uwp.nuspec
HISTORY.md
README.md

* CMake project updates
* meshconvert: Fix minor display issue with error messages
* meshconvert: Supports Long Paths on Windows 10, Version 1607 or later

June 2023 release

---

build/DirectXMesh-config.cmake.in

The CMakeLists.txt no longer mandates both **directxmath** and **directx-headers** packages be found unless building with MinGW or for Linux. This fixes the behavior for CMake clients consuming this package from VCPKG.

CMake target file fix

---

CMakeLists.txt
build/DirectXMesh-config.cmake.in

WIth the changes to make use of DirectXMath & DirectX-Headers 'optional' for VCPKG scenarios unless using MinGW -or- Linux, the generated targets file needed more robust handling of these targets.
Also made sure that explicit 'scope' is used consistently with all CMake ``target_`` commands.

CMake targets fixes for optional vs. required packages

---

DirectXMesh/DirectXMeshP.h

The CMake scenario already disables the new clang v16 warning, but if you upgrade the VCXPROJ project to clangcl, it reappears.

Suppress some additional clang v16 warnings when upgrading to clangcl

---

.nuget/directxmesh_uwp.nuspec
CMakePresets.json
DirectXMesh/DirectXMesh_Windows10_2019.vcxproj
DirectXMesh/DirectXMesh_Windows10_2022.vcxproj
DirectXMesh_Windows10_2019.sln
DirectXMesh_Windows10_2022.sln
build/DirectXMesh-GitHub-CMake-Dev17.yml
build/DirectXMesh-GitHub-CMake.yml
build/DirectXMesh-GitHub-Dev17.yml
build/DirectXMesh-GitHub-SDK-prerelease.yml
build/DirectXMesh-GitHub-SDK-release.yml
build/DirectXMesh-GitHub.yml
build/Directory.Build.props

32-bit ARM support is being deprecated for the UWP platform, and support is being removed from newer ARM-based CPUs and the Windows 11 OS.
> 32-bit ARM was never officially supported for Win32 desktop development.
See [Microsoft Learn](https://learn.microsoft.com/windows/arm/arm32-to-arm64)

AArch32 (ARM32) architecture deprecation

---

build/DirectXMesh-GitHub-MinGW.yml
build/DirectXMesh-GitHub-Test-Dev17.yml

The latest **windows-2022** ADO image no longer includes the Ninja build tool by default. It had been pulled in by another component as a dependency but is no longer there. The official solution is to install ninja using the Chocolatey package manager which part of the base image.
The latest update upgraded MinGW-W64 to 12.2, so I no longer need to explicitly install it for that pipeline.

Update build pipelines for recent changes to windows-2022 ADO images

---

Meshconvert/Meshconvert.cpp

The file list processing failed with filenames with spaces in them. This fixes the parsing to be line-by-line explicitly.

Fixed -flist handling for filenames with spaces

---

Utilities/FlexibleVertexFormat.h

They are used in file anyway. Making entire file use one kind of types (from cstdint) instead of another (from WINAPI) makes this header more portable.

FlexibleVertexFormat.h: use standard C fixed-width types instead of WINAPI ones

---

DirectXMesh/DirectXMesh_GDK_2019.vcxproj
DirectXMesh/DirectXMesh_GDK_2022.vcxproj
build/DirectXMesh-GitHub-WSL-11.yml
build/DirectXMesh-GitHub-WSL.yml

* Added a target to the GDK projects to provide a more actionable error message in the case of the GDK not being installed -or- the VS integration is missing.
* Updated YAML because the `-o` parameter is ambiguous for modern PowerShell.

Update GDK projects and ADO pipelines

---

Meshconvert/Meshconvert_Desktop_2019.vcxproj
Meshconvert/Meshconvert_Desktop_2019_Win10.vcxproj

The `/CETCOMPAT` linker flag is already enabled for EXEs build by VS 2022, but is also supported by VS 2019 (16.11) via `AdditionalOptions`.

Enable /CETCOMPAT when building with VS 2019

---

build/CompilerAndLinker.cmake
build/DirectXMesh-GitHub-Dev17.yml
build/DirectXMesh-GitHub-GDK-Dev17.yml
build/DirectXMesh-GitHub-Test-Dev17.yml
build/DirectXMesh-GitHub-WSL-11.yml

* GNU still defaults to x87 math code-gen on x86, so this opts into SSE/SSE2 math generation.

Update compiler build settings for CMake

---

CMakeLists.txt
build/CompilerAndLinker.cmake

Update to keep in sync with other projects.

CMake code review

---

.github/dependabot.yml
.github/workflows/bvt.yml
.github/workflows/vcpkg.yml
.github/workflows/wsl.yml
build/DirectXMesh-GitHub-MinGW.yml
build/DirectXMesh-GitHub-Test-Dev17.yml
build/DirectXMesh-GitHub-Test.yml
build/DirectXMesh-GitHub-WSL-11.yml
build/DirectXMesh-GitHub-WSL.yml
build/DirectXMesh-SDL.yml

This builds the test suite such that it only needs a few test data files which are included directly in the test repo. This avoids LFS bandwidth traffic for the full set of test data.
> Includes ADO YAML code review to clean up use of PATs, and to convert all use of vcpkg in the pipelines to 'manifest mode'.
> Also sets the dependabot to not spam quite so often for GHA.

Add GitHub Action for BVTs with subset of tests

---

README.md
build/DirectXMesh-GitHub-SDK-prerelease.yml
build/DirectXMesh-GitHub-SDK-release.yml

As of Windows SDK version 10.0.26100.1834, ARM64 for Win32 "classic" Desktop no longer builds with the VS 2019 toolset. VS 2022 is required.

VS 2019 Win32 on ARM64 is no longer supported

---

DirectXMesh/DirectXMesh.h
DirectXMesh/DirectXMesh.inl
Meshconvert/Meshconvert.cpp

Originally I used `DWORD` for flags. When I removed Windows-specific types, I changed it to `unsigned long` to keep the signature the same. The ask is to use `uint32_t` instead which is more consistent on Windows vs. Linux.
Also removed 'extra-semi' for macro.

Use fixed width integers for underlying enum types

---

Meshconvert/Meshconvert.cpp

Embraces the `-so` vs. `--long-option` GNU-like pattern for the command-line tool.
This also adds `-o=value` which is the GNU standard and the tool already supported `-o:value` or `-o value`.
> This is a hybrid of the Windows style and GNU-like pattern. For example, you can't combine single-characters together such as  `-yl` with this tool like you can with GNU-style argument syntax. Not all multi-character options use `--` which would be the GNU standard.
> The tool already supports the `-- ` escape so you can start filenames with `/` or `-`

Convert meshconvert tool to use GNU-style long options

---

.github/workflows/wsl.yml

GNUC 10 and 11 not included in Linux runner image anymore. Now has GNUC 12, 13, and 14.

GHA Linux runner updated

---

.github/workflows/vcpkg.yml
.github/workflows/wsl.yml

In restricted workflows, there's no access to the repository variable that gives the latest stable VCPKG commit id. This adds logic to use the head commit id from the VCPKG registry if the variable isn't set.

Update VCPKG GHAs to use head commit id if variable isn't set

---

.github/workflows/main.yml
.github/workflows/test.yml
.github/workflows/wsl.yml
CMakeLists.txt
DirectXMesh/DirectXMesh.h
build/DirectXMesh.rc.in
build/versioninfo.ps1

Uses `BUILD_SHARED_LIBS` standard CMake option to build as a DLL/so vs. a static C++ library.

Add option to build as shared lib

---

DirectXMesh/DirectXMeshConcat.cpp
DirectXMesh/DirectXMeshVBReader.cpp
DirectXMesh/DirectXMeshletGenerator.cpp
Meshconvert/Mesh.cpp
Meshconvert/Meshconvert.cpp

Both ``const auto`` and ``auto const`` are equivalent in terms of the C++ compiler parser, but general coding guidelines suggest using ``const auto``. The primary reason for this PR is to be consistent since the codebase was using both.

Code review for const auto vs auto const

---

DirectXMesh/DirectXMesh.h

The check in for #198 resulted in a build warning for VBReader and VBWriter. This PR fixes that warning.

Fix warning C4251 when building with shared libs

---

build/DirectXMesh-GitHub-CMake.yml
build/DirectXMesh-GitHub-Test.yml
build/DirectXMesh-GitHub.yml

Remove cases of building for ARM64 with VS 2019 due to changes to Windows SDK (26100).

Update ADO coverage for clang v12

---

.nuget/directxmesh_desktop_2019.nuspec
.nuget/directxmesh_desktop_win10.nuspec
.nuget/directxmesh_uwp.nuspec
CHANGELOG.md
CMakeLists.txt
DirectXMesh/DirectXMesh.h
README.md

* Retired support for Windows 7 and Windows 8.0
* CMake project updates including support for BUILD_SHARED_LIBS (i.e. DLL vs. static library)

March 24, 2025

---

.azuredevops/policies/approvercountpolicy.yml
DirectXMesh/DirectXMesh.h

CoPilot suggested a change which I disagreed with, but when I researched it a bit I realized there was a different change that would be useful to prefer `__attribute__` to `__declspec` for GNUC.
> Also includes some AzureDev Ops polices from the production pipelines.

Code review feedback for DLL declimport/export

---

Meshconvert/Mesh.cpp

This hardening is already present in the *DirectX Tool Kit* loading code for VBO.

Add overflow check for VBO reader for meshconvert

---

.github/workflows/bvt.yml
.github/workflows/main.yml
.github/workflows/test.yml
.github/workflows/vcpkg.yml
.github/workflows/wsl.yml

Switched all impacted pipelines to use *windows-2022*, but I still make use of v142 toolset for validation of the "VS 2019 (16.11)" compiler.

GitHub Actions windows-2019 runner is being retired

---

DirectXMesh/DirectXMeshletGenerator.cpp

fixes https://github.com/microsoft/DirectXMesh/issues/235
if value behind adj[i] is equal to endIndex, we are outside the subset.

Fix adjacency guard condition causing subscript out of range

---

DirectXMesh/DirectXMeshUtil.cpp

PR #243 introduced this PREFIX warning:
> DirectXMeshUtil.cpp(267) : warning C6101: Returning uninitialized memory '*strides'.  A successful path through the function does not set the named _Out_ parameter. : Lines: 267, 271, 273, 274, 267
Which this PR fixes.

Fix /analyze warning

---

CMakeLists.txt
CMakePresets.json
DirectXMesh/DirectXMeshClean.cpp
DirectXMesh/DirectXMeshOptimizeTVC.cpp
DirectXMesh/DirectXMeshletGenerator.cpp
README.md

* CMake 3.21 comes with VS 2022.
> VS 2019 users will need to install a standalone version of a CMake newer than the 3.20 that comes with it.
* Minor code review to return `E_UNEXPECTED` or `E_POINTER` in places that can't be hit in code paths even with invalid input args--i.e. defense-in-depth checks that make static code analysis happy.

Upgrade to CMake 3.21
